library(tidyverse)
library(tidymodels)
library(caret)
library(SSLR)
library(doParallel)
library(MLmetrics)


dataset1 <- read.csv("...1. Preprocessing\\Output\\sub1_valencearousal_4_clases.csv")
dataset2 <- read.csv("...1. Preprocessing\\Output\\sub2_valencearousal_4_clases.csv")
dataset3 <- read.csv("...1. Preprocessing\\Output\\sub3_valencearousal_4_clases.csv")
dataset4 <- read.csv("...1. Preprocessing\\Output\\sub4_valencearousal_4_clases.csv")
dataset5 <- read.csv("...1. Preprocessing\\Output\\sub5_valencearousal_4_clases.csv")
dataset6 <- read.csv("...1. Preprocessing\\Output\\sub6_valencearousal_4_clases.csv")
dataset7 <- read.csv("...1. Preprocessing\\Output\\sub7_valencearousal_4_clases.csv")
dataset8 <- read.csv("...1. Preprocessing\\Output\\sub8_valencearousal_4_clases.csv")
dataset9 <- read.csv("...1. Preprocessing\\Output\\sub9_valencearousal_4_clases.csv")
dataset10 <- read.csv("...1. Preprocessing\\Output\\sub10_valencearousal_4_clases.csv")
dataset11 <- read.csv("...1. Preprocessing\\Output\\sub11_valencearousal_4_clases.csv")
dataset12 <- read.csv("...1. Preprocessing\\Output\\sub12_valencearousal_4_clases.csv")
dataset13 <- read.csv("...1. Preprocessing\\Output\\sub13_valencearousal_4_clases.csv")
dataset14 <- read.csv("...1. Preprocessing\\Output\\sub14_valencearousal_4_clases.csv")
dataset15 <- read.csv("...1. Preprocessing\\Output\\sub15_valencearousal_4_clases.csv")
dataset16 <- read.csv("...1. Preprocessing\\Output\\sub16_valencearousal_4_clases.csv")
dataset17 <- read.csv("...1. Preprocessing\\Output\\sub17_valencearousal_4_clases.csv")
dataset18 <- read.csv("...1. Preprocessing\\Output\\sub18_valencearousal_4_clases.csv")
dataset19 <- read.csv("...1. Preprocessing\\Output\\sub19_valencearousal_4_clases.csv")
dataset20 <- read.csv("...1. Preprocessing\\Output\\sub20_valencearousal_4_clases.csv")
dataset21 <- read.csv("...1. Preprocessing\\Output\\sub21_valencearousal_4_clases.csv")
dataset22 <- read.csv("...1. Preprocessing\\Output\\sub22_valencearousal_4_clases.csv")
dataset23 <- read.csv("...1. Preprocessing\\Output\\sub23_valencearousal_4_clases.csv")
dataset24 <- read.csv("...1. Preprocessing\\Output\\sub24_valencearousal_4_clases.csv")
dataset25 <- read.csv("...1. Preprocessing\\Output\\sub25_valencearousal_4_clases.csv")
dataset26 <- read.csv("...1. Preprocessing\\Output\\sub26_valencearousal_4_clases.csv")
dataset27 <- read.csv("...1. Preprocessing\\Output\\sub27_valencearousal_4_clases.csv")
dataset28 <- read.csv("...1. Preprocessing\\Output\\sub28_valencearousal_4_clases.csv")
dataset29 <- read.csv("...1. Preprocessing\\Output\\sub29_valencearousal_4_clases.csv")
dataset30 <- read.csv("...1. Preprocessing\\Output\\sub30_valencearousal_4_clases.csv")
confusionMatrix_list<-list()
set.seed(1)
for (i in 1:30){ 
  array_num <- 1:30
  array_num <- array_num[- i]  
  dataset <- rbind(eval(parse(text = paste("dataset", array_num[1],sep = ""))),eval(parse(text = paste("dataset", array_num[2],sep = ""))),eval(parse(text = paste("dataset", array_num[3],sep = ""))),eval(parse(text = paste("dataset", array_num[4],sep = ""))),eval(parse(text = paste("dataset", array_num[5],sep = ""))),eval(parse(text = paste("dataset", array_num[6],sep = ""))),eval(parse(text = paste("dataset", array_num[7],sep = ""))),eval(parse(text = paste("dataset", array_num[8],sep = ""))),eval(parse(text = paste("dataset", array_num[9],sep = ""))),eval(parse(text = paste("dataset", array_num[10],sep = ""))),eval(parse(text = paste("dataset", array_num[11],sep = ""))),eval(parse(text = paste("dataset", array_num[12],sep = ""))),eval(parse(text = paste("dataset", array_num[13],sep = ""))),eval(parse(text = paste("dataset", array_num[14],sep = ""))),eval(parse(text = paste("dataset", array_num[15],sep = ""))),eval(parse(text = paste("dataset", array_num[16],sep = ""))),eval(parse(text = paste("dataset", array_num[17],sep = ""))),eval(parse(text = paste("dataset", array_num[18],sep = ""))),eval(parse(text = paste("dataset", array_num[19],sep = ""))),eval(parse(text = paste("dataset", array_num[20],sep = ""))),eval(parse(text = paste("dataset", array_num[21],sep = ""))),eval(parse(text = paste("dataset", array_num[22],sep = ""))),eval(parse(text = paste("dataset", array_num[23],sep = ""))),eval(parse(text = paste("dataset", array_num[24],sep = ""))),eval(parse(text = paste("dataset", array_num[25],sep = ""))),eval(parse(text = paste("dataset", array_num[26],sep = ""))),eval(parse(text = paste("dataset", array_num[27],sep = ""))),eval(parse(text = paste("dataset", array_num[28],sep = ""))),eval(parse(text = paste("dataset", array_num[29],sep = ""))))
  dataset <- transform(dataset, valencearousal = as.factor(valencearousal))
  labeled.index <- createDataPartition(dataset$valencearousal, p = .2, list = FALSE)
  train<- dataset[labeled.index,]
  test <- eval(parse(text = paste("dataset", i,sep = "")))
  cl <- makePSOCKcluster(10)
  registerDoParallel(cl)
  fit.lda <- train(valencearousal~., data=train,method="rf", ntree=100, metric="Accuracy")
  predictions <- predict(fit.lda, test)
  stopCluster(cl)
  data <- factor(predictions, levels = c('1', '2','3','4'))
  reference <- factor(test$valencearousal, levels = c('1', '2','3','4'))
  confusionMatrix <- confusionMatrix(data=data, reference=reference,mode = "prec_recall")
  print(i)
  print(confusionMatrix)
  confusionMatrix_list <- append(confusionMatrix_list,list(confusionMatrix))
  rm(dataset,test,train,fit.lda,array_num,predictions, data,reference, confusionMatrix,cl)
}  